# -*- coding: utf-8 -*-
"""4110E017.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BaZGX3dcc1ch6ev96W9lOFbFo_c053UO
"""

x = input('Enter your name:')
print('Hello, ' + x)

type(x)

a = int(input("請輸入："))
a

type(a)

b=a+1
b

a,b = eval(input("請輸入兩個數位："))
a,b